name: Mirror Repo Without Submodules

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4.2.0
      with:
        submodules: true

    - name: Convert submodules to regular directories
      uses: Sinan-Karakaya/orga-to-monorepo-action@1d3e15a5da24948452ef8c26729b20e1bd155026
      with:
        target_monorepo_url: git@github.com:Sinan-Karakaya/test_push_target.git
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
